application: github-notifications-glass
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:

- url: /images
  static_dir: static/images

- url: /glass/(.*\.(html|css|js|grxml))
  static_files: static/glass/\1
  upload: static/glass/(.*\.(html|css|js|grxml))

- url: /js/service\.js
  static_files: static/service/service.js
  upload: static/service/service\.js

- url: /css/service\.css
  static_files: static/service/service.css
  upload: static/service/service\.css

- url: /_ah/spi/.*
  script: apis.ApiServer

- url: .*
  script: main.app

libraries:
- name: pycrypto
  version: latest

- name: jinja2
  version: latest

- name: PIL
  version: latest
